device: cuda

negative_inpainting_prompt: "collage, text, writings, signs, text, white border, photograph border, artifacts, blur, blurry, foggy, fog, person, bad quality, distortions, distorted image, watermark, signature, fisheye look"
num_frames: 1
frames: 5
seed: 2

# Indoor scene requires Marigold for better depth estimation of interior spaces
depth_model: marigold
# Slower camera movement for smoother indoor rotation
camera_speed: 0.0008
# Full 360 degree rotation
rotation_range: 1.0

# Camera parameters for indoor scene
init_focal_length: 800

# Decoder finetuning parameters
finetune_depth_decoder: True
decoder_learning_rate: 0.0001
num_finetune_decoder_steps: 150
num_finetune_decoder_steps_interp: 40
preservation_weight: 12

# Inpainting parameters
stable_diffusion_checkpoint: "stabilityai/stable-diffusion-2-inpainting"
inpainting_resolution_interp: 512
inpainting_resolution_gen: 512

# Depth finetuning parameters
depth_conditioning: True
depth_model_learning_rate: 1e-6

save_fps: 30
skip_interp: False
skip_gen: False
kf2_upsample_coef: 4
# Reduced depth range for indoor scenes
fg_depth_range: 0.015
depth_shift: 0.001

# Adjusted for indoor scene
sky_hard_depth: 0.02
sky_erode_kernel_size: 0
ground_erode_kernel_size: 3
dilate_mask_decoder_ft: 3

regenerate_times: 3
debug: False

# Disable sky generation for indoor scene
gen_sky: False
gen_layer: True

# Pure rotation without translation
camera_speed_multiplier_rotation: 1.0
api_key: "Your OpenAI api_key"
gen_sky_image: False

use_compile: False
# Full 360-degree rotation pattern
rotation_path: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
num_scenes: 16
use_free_lunch: False
runs_dir: "/home/tanisha/vqa_nms/WonderWorld/output/"